n1 = int(input('Digite um número:'))
n2 = int(input('Digite outro número:'))
print(f'A some entre {n1} e {n2} é {n1+n2}', end=' .')
print(f'A subtração {n1-n2}', end=' .')
print(f'O produto {n1*n2}', end=' .')
print(f'A potência de base {n1} e exponente {n2} é igual a {n1**n2}', end=' .')
print(f'A divisão {(n1/n2):.3f}', end=' .')
print(f'A divisâo inteira {n1//n2}', end=' .')
print(f'O resto da divisão {n1%n2}')
