n = int(input('Você quer saber a tabuada de qual número?'))
print(
    f'Você escolheu o número {n}. Sua tabuada é:\n{n} x 1 = {n * 1}\n{n} x 2 = {n * 2}\n{n} x 3 = {n * 3}\n{n} x 4 = {n * 4}\n{n} x 5 = {n * 5}\n{n} x 6 = {n * 6}\n{n} x 7 = {n * 7}\n{n} x 8 = {n * 8}\n{n} x 9 = {n * 9}\n{n} x 10 = {n * 10}')
# ou
print(f'Você escolheu o número {n}, sua tabuada é:')
print(f'{n} x 1 = {n * 1}')
print(f'{n} x 2 = {n * 2}')
print(f'{n} x 3 = {n * 3}')
print(f'{n} x 4 = {n * 4}')
print(f'{n} x 5 = {n * 5}')
print(f'{n} x 6 = {n * 6}')
print(f'{n} x 7 = {n * 7}')
print(f'{n} x 8 = {n * 8}')
print(f'{n} x 9 = {n * 9}')
print(f'{n} x 10 = {n * 10}')
